export const Segments = [
  {
    alias: "肠系膜动脉",
    name: "ph_sma",
    dataName: "Segmentation preview_Segment_1.stl",
    visible: true,
    color: 0x146975,
  },
  {
    alias: "左锁骨下动脉",
    name: "ph_lsa",
    dataName: "Segmentation preview_Segment_2.stl",
    visible: true,
    color: 0x83363c,
  },
  {
    alias: "右颈总动脉",
    name: "ph_rcca",
    dataName: "Segmentation preview_Segment_3.stl",
    visible: true,
    color: 0x937eb2,
  },
  {
    alias: "右肾动脉",
    name: "ph_rra",
    dataName: "Segmentation preview_Segment_4.stl",
    visible: true,
    color: 0xa6896a,
  },
  {
    alias: "左肾动脉",
    name: "ph_lra",
    dataName: "Segmentation preview_Segment_5.stl",
    visible: true,
    color: 0xff0000,
  },
  {
    alias: "右锁骨下动脉",
    name: "ph_rsa",
    dataName: "Segmentation preview_Segment_6.stl",
    visible: true,
    color: 0xff0000,
  },
  {
    alias: "右髂总动脉",
    name: "ph_rcia",
    dataName: "Segmentation preview_Segment_7.stl",
    visible: true,
    color: 0xc2854f,
  },
  {
    alias: "腹腔干",
    name: "ph_ca",
    dataName: "Segmentation preview_Segment_8.stl",
    visible: true,
    color: 0xa6757c,
  },
  {
    alias: "左颈总动脉",
    name: "ph_lcca",
    dataName: "Segmentation preview_Segment_9.stl",
    visible: true,
    color: 0xa6acaf,
  },
  {
    alias: "主动脉",
    name: "ph_ao",
    dataName: "Segmentation preview_Segment_10.stl",
    visible: true,
    color: 0xff0000,
  },
  {
    alias: "股骨头",
    name: "ph_fe",
    dataName: "Segmentation preview_Segment_11.stl",
    visible: true,
    color: 0x646246,
  },
  {
    alias: "头臂干",
    name: "ph_bct",
    dataName: "Segmentation preview_Segment_12.stl",
    visible: true,
    color: 0x517798,
  },
  {
    alias: "主动脉钙化",
    name: "ph_ac",
    dataName: "Segmentation preview_Segment_13.stl",
    visible: true,
    color: 0x5b7da3,
  },
  {
    alias: "左室",
    name: "ph_lv",
    dataName: "Segmentation preview_Segment_14.stl",
    visible: true,
    color: 0x5b7da3,
  },
  {
    alias: "左髂总动脉",
    name: "ph_lcia",
    dataName: "Segmentation preview_Segment_15.stl",
    visible: true,
    color: 0x8e4828,
  }
];
